### ISSUE TITLE
Inccorect naming convention

### ISSUE THREAD

**Issue by maietta** [romantomjak/shoutcast#3]
In regard to Shoutcast or Icecast, a "client" is not the listener, but rather the streaming source.

You should probably consider renaming this project something like a "Shoutcast Player" or "Shoutcast Capturer" which more accurately describes what this utility does.

A Shoutcast client sends audio to a shoutcast server, which in turn lets people stream audio from to their players.

**Comment by romantomjak** [comment]
Thanks, but to me personally client makes more sense since "clients" are traditionally used for connecting to "servers" to do whatever they need to do. This is also true from the perspective of software developers as they will build "clients" to interact with the remote shoutcast "server" which in this case is simply consuming the stream.

**Comment by maietta** [comment]
> Thanks, but to me personally client makes more sense since "clients" are traditionally used for connecting to "servers" to do whatever they need to do. This is also true from the perspective of software developers as they will build "clients" to interact with the remote shoutcast "server" which in this case is simply consuming the stream.

Thanks for the response.
